sudo: required
services:
  - docker

before_install:
  - docker build -t btkoanh/docker-react-test -f Dockerfile.dev . \ --build-arg NPM_REGISTRY=https://registry.npmmirror.com \ -t btkoanh/docker-react-test 

script:
  - docker run -e CI=true btkoanh/docker-react-test npm run test -- --coverage