sudo: required
services:
  - docker

before_install:
  - docker build -t btkoanh/docker-react-test -f Dockerfile.dev . 

script:
  - docker run -e CI=true btkoanh/docker-react-test npm run test -- --coverage
  - docker build -f Dockerfile.dev . -t btkoanh/docker-react-test
  - docker run btkoanh/docker-react-test npm run test